/** Schema relation metadata for trash visibility. Verified against schema.prisma by tests. */
export interface ModelMetadata {
  table: string;
  trash: boolean;
  relations: Record<
    string,
    { model: string; many: boolean; optional: boolean; fields: string[] }
  >;
}
export const modelMap: Record<string, ModelMetadata> = {
  User: {
    table: "users",
    trash: false,
    relations: {
      createdOrderPackages: {
        model: "OrderPackage",
        many: true,
        optional: false,
        fields: [],
      },
      updatedOrderPackages: {
        model: "OrderPackage",
        many: true,
        optional: false,
        fields: [],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      createdUsers: {
        model: "User",
        many: true,
        optional: false,
        fields: [],
      },
      updatedUsers: {
        model: "User",
        many: true,
        optional: false,
        fields: [],
      },
      managedProjects: {
        model: "Project",
        many: true,
        optional: false,
        fields: [],
      },
      createdClients: {
        model: "Client",
        many: true,
        optional: false,
        fields: [],
      },
      updatedClients: {
        model: "Client",
        many: true,
        optional: false,
        fields: [],
      },
      createdSuppliers: {
        model: "Supplier",
        many: true,
        optional: false,
        fields: [],
      },
      updatedSuppliers: {
        model: "Supplier",
        many: true,
        optional: false,
        fields: [],
      },
      createdProjects: {
        model: "Project",
        many: true,
        optional: false,
        fields: [],
      },
      updatedProjects: {
        model: "Project",
        many: true,
        optional: false,
        fields: [],
      },
      createdBuildings: {
        model: "Building",
        many: true,
        optional: false,
        fields: [],
      },
      updatedBuildings: {
        model: "Building",
        many: true,
        optional: false,
        fields: [],
      },
      createdOrders: {
        model: "ProcurementOrder",
        many: true,
        optional: false,
        fields: [],
      },
      updatedOrders: {
        model: "ProcurementOrder",
        many: true,
        optional: false,
        fields: [],
      },
      linkedOrderBuildings: {
        model: "ProcurementOrderBuilding",
        many: true,
        optional: false,
        fields: [],
      },
      createdCostLines: {
        model: "ProcurementOrderCostLine",
        many: true,
        optional: false,
        fields: [],
      },
      updatedCostLines: {
        model: "ProcurementOrderCostLine",
        many: true,
        optional: false,
        fields: [],
      },
      createdVatEntries: {
        model: "ProcurementOrderVatEntry",
        many: true,
        optional: false,
        fields: [],
      },
      updatedVatEntries: {
        model: "ProcurementOrderVatEntry",
        many: true,
        optional: false,
        fields: [],
      },
      createdPaymentInstallments: {
        model: "PaymentInstallment",
        many: true,
        optional: false,
        fields: [],
      },
      updatedPaymentInstallments: {
        model: "PaymentInstallment",
        many: true,
        optional: false,
        fields: [],
      },
      createdPaymentSettlements: {
        model: "PaymentSettlement",
        many: true,
        optional: false,
        fields: [],
      },
      updatedPaymentSettlements: {
        model: "PaymentSettlement",
        many: true,
        optional: false,
        fields: [],
      },
      processedSupplierQuotes: {
        model: "SupplierQuoteImport",
        many: true,
        optional: false,
        fields: [],
      },
      auditEvents: {
        model: "AuditEvent",
        many: true,
        optional: false,
        fields: [],
      },
      createdApplicationSettings: {
        model: "ApplicationSetting",
        many: true,
        optional: false,
        fields: [],
      },
      updatedApplicationSettings: {
        model: "ApplicationSetting",
        many: true,
        optional: false,
        fields: [],
      },
      createdRooms: {
        model: "Room",
        many: true,
        optional: false,
        fields: [],
      },
      updatedRooms: {
        model: "Room",
        many: true,
        optional: false,
        fields: [],
      },
      createdLogisticsLocations: {
        model: "LogisticsLocation",
        many: true,
        optional: false,
        fields: [],
      },
      updatedLogisticsLocations: {
        model: "LogisticsLocation",
        many: true,
        optional: false,
        fields: [],
      },
      createdItems: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
      updatedItems: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
      itemImports: {
        model: "ItemImport",
        many: true,
        optional: false,
        fields: [],
      },
      createdClientBillingDocuments: {
        model: "ClientBillingDocument",
        many: true,
        optional: false,
        fields: [],
      },
      updatedClientBillingDocuments: {
        model: "ClientBillingDocument",
        many: true,
        optional: false,
        fields: [],
      },
      createdClientPaymentInstallments: {
        model: "ClientPaymentInstallment",
        many: true,
        optional: false,
        fields: [],
      },
      updatedClientPaymentInstallments: {
        model: "ClientPaymentInstallment",
        many: true,
        optional: false,
        fields: [],
      },
      createdClientReceipts: {
        model: "ClientReceipt",
        many: true,
        optional: false,
        fields: [],
      },
      updatedClientReceipts: {
        model: "ClientReceipt",
        many: true,
        optional: false,
        fields: [],
      },
      createdClientBillingAllocations: {
        model: "ClientBillingAllocation",
        many: true,
        optional: false,
        fields: [],
      },
      updatedClientBillingAllocations: {
        model: "ClientBillingAllocation",
        many: true,
        optional: false,
        fields: [],
      },
      processedClientDocuments: {
        model: "ClientDocumentImport",
        many: true,
        optional: false,
        fields: [],
      },
      createdProjectFreightExpenses: {
        model: "ProjectFreightExpense",
        many: true,
        optional: false,
        fields: [],
      },
      updatedProjectFreightExpenses: {
        model: "ProjectFreightExpense",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  Currency: {
    table: "currencies",
    trash: false,
    relations: {
      unassignedCashOriginal: {
        model: "UnassignedCashRecord",
        many: true,
        optional: false,
        fields: [],
      },
      unassignedCashReporting: {
        model: "UnassignedCashRecord",
        many: true,
        optional: false,
        fields: [],
      },
      clients: {
        model: "Client",
        many: true,
        optional: false,
        fields: [],
      },
      suppliers: {
        model: "Supplier",
        many: true,
        optional: false,
        fields: [],
      },
      projects: {
        model: "Project",
        many: true,
        optional: false,
        fields: [],
      },
      orders: {
        model: "ProcurementOrder",
        many: true,
        optional: false,
        fields: [],
      },
      sellingOrders: {
        model: "ProcurementOrder",
        many: true,
        optional: false,
        fields: [],
      },
      paymentInstallments: {
        model: "PaymentInstallment",
        many: true,
        optional: false,
        fields: [],
      },
      applicationSettings: {
        model: "ApplicationSetting",
        many: true,
        optional: false,
        fields: [],
      },
      items: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
      clientBillingDocuments: {
        model: "ClientBillingDocument",
        many: true,
        optional: false,
        fields: [],
      },
      clientPaymentInstallments: {
        model: "ClientPaymentInstallment",
        many: true,
        optional: false,
        fields: [],
      },
      projectFreightExpenses: {
        model: "ProjectFreightExpense",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  Client: {
    table: "clients",
    trash: true,
    relations: {
      defaultCurrency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["defaultCurrencyCode"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      projects: {
        model: "Project",
        many: true,
        optional: false,
        fields: [],
      },
      billingDocuments: {
        model: "ClientBillingDocument",
        many: true,
        optional: false,
        fields: [],
      },
      documentImports: {
        model: "ClientDocumentImport",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  Supplier: {
    table: "suppliers",
    trash: true,
    relations: {
      defaultCurrency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["defaultCurrencyCode"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      orders: {
        model: "ProcurementOrder",
        many: true,
        optional: false,
        fields: [],
      },
      quoteImports: {
        model: "SupplierQuoteImport",
        many: true,
        optional: false,
        fields: [],
      },
      items: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
      itemImports: {
        model: "ItemImport",
        many: true,
        optional: false,
        fields: [],
      },
      freightExpenses: {
        model: "ProjectFreightExpense",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  Project: {
    table: "projects",
    trash: true,
    relations: {
      orderPackages: {
        model: "OrderPackage",
        many: true,
        optional: false,
        fields: [],
      },
      client: {
        model: "Client",
        many: false,
        optional: false,
        fields: ["clientId"],
      },
      reportingCurrency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["reportingCurrencyCode"],
      },
      projectManager: {
        model: "User",
        many: false,
        optional: true,
        fields: ["projectManagerId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      buildings: {
        model: "Building",
        many: true,
        optional: false,
        fields: [],
      },
      orders: {
        model: "ProcurementOrder",
        many: true,
        optional: false,
        fields: [],
      },
      quoteImports: {
        model: "SupplierQuoteImport",
        many: true,
        optional: false,
        fields: [],
      },
      items: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
      itemImports: {
        model: "ItemImport",
        many: true,
        optional: false,
        fields: [],
      },
      billingDocuments: {
        model: "ClientBillingDocument",
        many: true,
        optional: false,
        fields: [],
      },
      documentImports: {
        model: "ClientDocumentImport",
        many: true,
        optional: false,
        fields: [],
      },
      freightExpenses: {
        model: "ProjectFreightExpense",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  Building: {
    table: "buildings",
    trash: true,
    relations: {
      project: {
        model: "Project",
        many: false,
        optional: false,
        fields: ["projectId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      orders: {
        model: "ProcurementOrderBuilding",
        many: true,
        optional: false,
        fields: [],
      },
      rooms: {
        model: "Room",
        many: true,
        optional: false,
        fields: [],
      },
      items: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  ProcurementOrder: {
    table: "procurement_orders",
    trash: true,
    relations: {
      orderPackage: {
        model: "OrderPackage",
        many: false,
        optional: true,
        fields: ["packageId", "projectId"],
      },
      project: {
        model: "Project",
        many: false,
        optional: false,
        fields: ["projectId"],
      },
      supplier: {
        model: "Supplier",
        many: false,
        optional: false,
        fields: ["supplierId"],
      },
      orderCurrency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["orderCurrencyCode"],
      },
      sellingCurrency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["sellingCurrencyCode"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      buildings: {
        model: "ProcurementOrderBuilding",
        many: true,
        optional: false,
        fields: [],
      },
      costLines: {
        model: "ProcurementOrderCostLine",
        many: true,
        optional: false,
        fields: [],
      },
      vatEntries: {
        model: "ProcurementOrderVatEntry",
        many: true,
        optional: false,
        fields: [],
      },
      paymentInstallments: {
        model: "PaymentInstallment",
        many: true,
        optional: false,
        fields: [],
      },
      quoteImports: {
        model: "SupplierQuoteImport",
        many: true,
        optional: false,
        fields: [],
      },
      items: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
      itemImports: {
        model: "ItemImport",
        many: true,
        optional: false,
        fields: [],
      },
      clientBillingAllocations: {
        model: "ClientBillingAllocation",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  ProjectFreightExpense: {
    table: "project_freight_expenses",
    trash: true,
    relations: {
      project: {
        model: "Project",
        many: false,
        optional: false,
        fields: ["projectId"],
      },
      supplier: {
        model: "Supplier",
        many: false,
        optional: true,
        fields: ["supplierId"],
      },
      currency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["currencyCode"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
    },
  },
  ProcurementOrderBuilding: {
    table: "procurement_order_buildings",
    trash: false,
    relations: {
      order: {
        model: "ProcurementOrder",
        many: false,
        optional: false,
        fields: ["orderId"],
      },
      building: {
        model: "Building",
        many: false,
        optional: false,
        fields: ["buildingId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
    },
  },
  ProcurementOrderCostLine: {
    table: "procurement_order_cost_lines",
    trash: false,
    relations: {
      order: {
        model: "ProcurementOrder",
        many: false,
        optional: false,
        fields: ["orderId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
    },
  },
  ProcurementOrderVatEntry: {
    table: "procurement_order_vat_entries",
    trash: false,
    relations: {
      order: {
        model: "ProcurementOrder",
        many: false,
        optional: false,
        fields: ["orderId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
    },
  },
  PaymentInstallment: {
    table: "payment_installments",
    trash: true,
    relations: {
      order: {
        model: "ProcurementOrder",
        many: false,
        optional: false,
        fields: ["orderId"],
      },
      currency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["currencyCode"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      settlements: {
        model: "PaymentSettlement",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  PaymentSettlement: {
    table: "payment_settlements",
    trash: true,
    relations: {
      installment: {
        model: "PaymentInstallment",
        many: false,
        optional: false,
        fields: ["installmentId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
    },
  },
  SupplierQuoteImport: {
    table: "supplier_quote_imports",
    trash: false,
    relations: {
      order: {
        model: "ProcurementOrder",
        many: false,
        optional: false,
        fields: ["orderId"],
      },
      project: {
        model: "Project",
        many: false,
        optional: false,
        fields: ["projectId"],
      },
      supplier: {
        model: "Supplier",
        many: false,
        optional: false,
        fields: ["supplierId"],
      },
      processedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["processedById"],
      },
    },
  },
  AuditEvent: {
    table: "audit_events",
    trash: false,
    relations: {
      actor: {
        model: "User",
        many: false,
        optional: true,
        fields: ["actorId"],
      },
    },
  },
  ApplicationSetting: {
    table: "application_settings",
    trash: false,
    relations: {
      companyReportingCurrency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["companyReportingCurrencyCode"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
    },
  },
  ClientBillingDocument: {
    table: "client_billing_documents",
    trash: true,
    relations: {
      client: {
        model: "Client",
        many: false,
        optional: false,
        fields: ["clientId"],
      },
      project: {
        model: "Project",
        many: false,
        optional: false,
        fields: ["projectId"],
      },
      currency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["currencyCode"],
      },
      supersedesDocument: {
        model: "ClientBillingDocument",
        many: false,
        optional: true,
        fields: ["supersedesDocumentId"],
      },
      revisions: {
        model: "ClientBillingDocument",
        many: true,
        optional: false,
        fields: [],
      },
      matchedInstallment: {
        model: "ClientPaymentInstallment",
        many: false,
        optional: true,
        fields: ["matchedInstallmentId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      paymentInstallments: {
        model: "ClientPaymentInstallment",
        many: true,
        optional: false,
        fields: [],
      },
      receipts: {
        model: "ClientReceipt",
        many: true,
        optional: false,
        fields: [],
      },
      allocations: {
        model: "ClientBillingAllocation",
        many: true,
        optional: false,
        fields: [],
      },
      imports: {
        model: "ClientDocumentImport",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  ClientPaymentInstallment: {
    table: "client_payment_installments",
    trash: true,
    relations: {
      billingDocument: {
        model: "ClientBillingDocument",
        many: false,
        optional: false,
        fields: ["billingDocumentId"],
      },
      currency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["currencyCode"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      receipts: {
        model: "ClientReceipt",
        many: true,
        optional: false,
        fields: [],
      },
      matchedInvoices: {
        model: "ClientBillingDocument",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  ClientReceipt: {
    table: "client_receipts",
    trash: true,
    relations: {
      billingDocument: {
        model: "ClientBillingDocument",
        many: false,
        optional: false,
        fields: ["billingDocumentId"],
      },
      installment: {
        model: "ClientPaymentInstallment",
        many: false,
        optional: true,
        fields: ["installmentId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
    },
  },
  ClientBillingAllocation: {
    table: "client_billing_allocations",
    trash: false,
    relations: {
      billingDocument: {
        model: "ClientBillingDocument",
        many: false,
        optional: false,
        fields: ["billingDocumentId"],
      },
      order: {
        model: "ProcurementOrder",
        many: false,
        optional: false,
        fields: ["orderId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
    },
  },
  ClientDocumentImport: {
    table: "client_document_imports",
    trash: false,
    relations: {
      billingDocument: {
        model: "ClientBillingDocument",
        many: false,
        optional: false,
        fields: ["billingDocumentId"],
      },
      client: {
        model: "Client",
        many: false,
        optional: false,
        fields: ["clientId"],
      },
      project: {
        model: "Project",
        many: false,
        optional: false,
        fields: ["projectId"],
      },
      processedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["processedById"],
      },
    },
  },
  Room: {
    table: "rooms",
    trash: true,
    relations: {
      building: {
        model: "Building",
        many: false,
        optional: false,
        fields: ["buildingId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      items: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  LogisticsLocation: {
    table: "logistics_locations",
    trash: false,
    relations: {
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      expectedWarehouseItems: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
      receivedWarehouseItems: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
      fabricatorItems: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
      destinationItems: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  ItemImport: {
    table: "item_imports",
    trash: false,
    relations: {
      project: {
        model: "Project",
        many: false,
        optional: false,
        fields: ["projectId"],
      },
      supplier: {
        model: "Supplier",
        many: false,
        optional: true,
        fields: ["supplierId"],
      },
      procurementOrder: {
        model: "ProcurementOrder",
        many: false,
        optional: true,
        fields: ["procurementOrderId"],
      },
      importedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["importedById"],
      },
      items: {
        model: "Item",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  Item: {
    table: "items",
    trash: true,
    relations: {
      project: {
        model: "Project",
        many: false,
        optional: false,
        fields: ["projectId"],
      },
      building: {
        model: "Building",
        many: false,
        optional: true,
        fields: ["buildingId"],
      },
      room: {
        model: "Room",
        many: false,
        optional: true,
        fields: ["roomId"],
      },
      supplier: {
        model: "Supplier",
        many: false,
        optional: true,
        fields: ["supplierId"],
      },
      procurementOrder: {
        model: "ProcurementOrder",
        many: false,
        optional: true,
        fields: ["procurementOrderId"],
      },
      itemImport: {
        model: "ItemImport",
        many: false,
        optional: true,
        fields: ["importId"],
      },
      purchaseCurrency: {
        model: "Currency",
        many: false,
        optional: true,
        fields: ["purchaseCurrencyCode"],
      },
      expectedWarehouse: {
        model: "LogisticsLocation",
        many: false,
        optional: true,
        fields: ["expectedWarehouseId"],
      },
      receivedWarehouse: {
        model: "LogisticsLocation",
        many: false,
        optional: true,
        fields: ["receivedWarehouseId"],
      },
      fabricator: {
        model: "LogisticsLocation",
        many: false,
        optional: true,
        fields: ["fabricatorId"],
      },
      destinationLocation: {
        model: "LogisticsLocation",
        many: false,
        optional: true,
        fields: ["destinationLocationId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
    },
  },
  OrderPackage: {
    table: "order_packages",
    trash: true,
    relations: {
      project: {
        model: "Project",
        many: false,
        optional: false,
        fields: ["projectId"],
      },
      createdBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["createdById"],
      },
      updatedBy: {
        model: "User",
        many: false,
        optional: true,
        fields: ["updatedById"],
      },
      orders: {
        model: "ProcurementOrder",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  TrashBatch: {
    table: "trash_batches",
    trash: false,
    relations: {
      records: {
        model: "TrashRecord",
        many: true,
        optional: false,
        fields: [],
      },
      dependencies: {
        model: "TrashDependency",
        many: true,
        optional: false,
        fields: [],
      },
    },
  },
  TrashRecord: {
    table: "trash_records",
    trash: false,
    relations: {
      batch: {
        model: "TrashBatch",
        many: false,
        optional: false,
        fields: ["batchId"],
      },
    },
  },
  TrashDependency: {
    table: "trash_dependencies",
    trash: false,
    relations: {
      batch: {
        model: "TrashBatch",
        many: false,
        optional: false,
        fields: ["batchId"],
      },
    },
  },
  UnassignedCashRecord: {
    table: "unassigned_cash_records",
    trash: true,
    relations: {
      currency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["currencyCode"],
      },
      reportingCurrency: {
        model: "Currency",
        many: false,
        optional: false,
        fields: ["reportingCurrencyCode"],
      },
    },
  },
};
