export { DEFAULT_AI_PROCESSING_MODEL as DEFAULT_CLIENT_DOCUMENT_EXTRACTION_MODEL } from "./ai-processing";
export const CLIENT_DOCUMENT_EXTRACTION_PROVIDER = "openai";
export const MAX_CLIENT_DOCUMENT_BYTES = 4 * 1024 * 1024;
export const MAX_CLIENT_DOCUMENT_LABEL = "4 MB";
export const ACCEPTED_CLIENT_DOCUMENT_TYPES = ".pdf,application/pdf";
