export const itemViewColumns = {
  financial: [
    "Reference / description",
    "Qty",
    "Unit purchase HT",
    "Purchase total HT",
    "Budget unit HT",
    "Budget total HT",
    "Markup %",
    "VAT treatment",
    "VAT %",
    "Recoverability",
    "Variance",
    "Variance comment",
    "Purchase-based freight allowance",
  ],
  general: [
    "Reference / description",
    "Project",
    "Building",
    "Room",
    "Supplier",
    "Qty",
    "Category",
    "Updated",
  ],
  status: [
    "Reference / description",
    "Supplier",
    "Commercial status",
    "Logistics status",
    "Vendor payment status",
  ],
  tracking: [
    "Reference / description",
    "Supplier",
    "Logistics status",
    "Fabricator",
    "Warehouse",
    "Expected fabricator",
    "Received fabricator",
    "Expected warehouse",
    "Received warehouse",
    "Transit / delivered / installed",
  ],
} as const;
