export const orderSortLabels = {
  updated: "Updated date",
  reference: "Reference",
  orderDate: "Order date",
  invoiceDate: "Invoice date",
  project: "Project",
  package: "Package",
  supplier: "Supplier",
  status: "Delivery status",
  purchase: "Purchase HT",
  paymentStatus: "Payment status",
  dueDate: "Payment due date",
  expectedDelivery: "Expected delivery",
  economicCost: "Economic Landed Cost HT",
  sell: "Total Order Sell HT",
  markup: "Planned Markup",
  payable: "Payable",
  scheduled: "Scheduled",
  paid: "Paid",
  outstanding: "Outstanding",
  expectedReady: "Expected ready",
  carrier: "Carrier",
  tracking: "Tracking reference",
} as const;

export type OrderSort = keyof typeof orderSortLabels;
export const orderSortFields = Object.keys(orderSortLabels) as OrderSort[];
export type OrderViewMode =
  "general" | "financial" | "supplier-payment" | "delivery";
export const orderViewColumns: Record<OrderViewMode, readonly OrderSort[]> = {
  general: [
    "reference",
    "project",
    "package",
    "supplier",
    "status",
    "purchase",
    "paymentStatus",
    "invoiceDate",
    "dueDate",
    "expectedDelivery",
  ],
  financial: [
    "reference",
    "supplier",
    "project",
    "package",
    "purchase",
    "economicCost",
    "sell",
    "markup",
  ],
  "supplier-payment": [
    "supplier",
    "reference",
    "project",
    "package",
    "payable",
    "scheduled",
    "paid",
    "outstanding",
    "dueDate",
    "paymentStatus",
  ],
  delivery: [
    "reference",
    "status",
    "expectedReady",
    "expectedDelivery",
    "supplier",
    "project",
    "package",
    "carrier",
    "tracking",
  ],
};
export const orderNumericColumns: readonly OrderSort[] = [
  "purchase",
  "economicCost",
  "sell",
  "markup",
  "payable",
  "scheduled",
  "paid",
  "outstanding",
];
